# Generated by Django 2.1.7 on 2019-12-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='lists.List'),
        ),
    ]
